services:
  db:
    image: postgres:18-alpine
    container_name: dgm-db
    environment:
      POSTGRES_DB: '${POSTGRES_DB:-dgmarket}'
      POSTGRES_USER: '${POSTGRES_USER:-dgmarket}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-verysecure}'
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
  
volumes:
  postgres_data: